### ISSUE TITLE
add sha256 info to release files

### ISSUE THREAD

**Issue by alltheseas** [zapstore/backlog#4]
it would be useful to also have the sha256 information in the same repository as the files

currently sha256 is found on the zap.store website

screenshot from github cli releases
![Screenshot from 2024-09-11 09-10-00](https://github.com/user-attachments/assets/526cf393-f4c5-417a-b95b-02487a7d49e4)

**Comment by franzaps** [comment]
What's the advantage of doing this?

**Comment by franzaps** [comment]
Hashes are in nostr kind0 for actually useful validation
